### ISSUE TITLE
Bad contrast on text highlights on Firefox?

### ISSUE THREAD

**Issue by korewaChino** [tau-OS/tau-helium#5]
### What Happened?

See title

### Steps to Reproduce

1. Use Helium GTK3 theme
2. Select text on dark background

### Expected Behavior

Proper contrast

### OS Version

Ultramarine Linux

### Software Version

Latest release (I have run all updates)

**Comment by lainsce** [comment]
Should be fixed in latest commits

**Comment by korewaChino** [comment]
It is *not* fixed in the newer commits, #7

**Comment by korewaChino** [comment]
Testing https://github.com/tau-OS/tau-helium/commit/8c96607da8454c8afb3e8696a11090ade49860e1, do not close yet

**Comment by korewaChino** [comment]
Update: this could also be a bug based on how Firefox selects colors.

I know this bug might sound trivial but users will eventually come over here complaining about our broken colors.

Minor/medium inconveinence
