### ISSUE TITLE
Unfocused Windows have broken colors

### ISSUE THREAD

**Issue by korewaChino** [tau-OS/tau-helium#6]
### What Happened?

Unfocused Windows have broken colors

https://github.com/tau-OS/tau-helium/assets/38139192/81eeb886-c875-4789-b8aa-97ef37bd8bda

### Steps to Reproduce

1. Unfocused GTK3 Window

### Expected Behavior

Proper colors(?)

### OS Version

Ultramarine Linux

### Software Version

Latest release (I have run all updates)

**Comment by lainsce** [comment]
As said in #design-staff, this isn't a bug. It's to differentiate unfocused from focused better.
